services:

  php:
    container_name: symfony_${app}_php
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - files_2:/var/www/symfony
      - /home/augc/docker/${app}/build/php/:/usr/local/etc/php/
    networks:
      symfony_net:
        ipv4_address: ${ip_php}

  nginx:
    container_name: symfony_${app]_nginx
    depends_on:
      - php
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - ${port}:80
    volumes:
      - files:/var/www/symfony/
      - /home/augc/docker/${app}/build/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      symfony_net:
        ipv4_address: ${ip_nginx}
    restart: always

volumes:
  files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/augc/docker/${app}/files


networks:
  symfony_net:
    external: true
